data:
  rating_files:
    - "data/combined_data_1.txt"
    - "data/combined_data_2.txt"
    - "data/combined_data_3.txt"
    - "data/combined_data_4.txt"
  probe_file: "data/probe.txt"
  movies_file: "data/movie_titles_fixed.csv"
  chunk_size: 100_000

output_dir: "checkpoints/"
model_path: "checkpoints/model.pth"

recommend:
  num_recommendations: 10
  movie_title: "Batman Begins"
  user_id: 2380848
