data:
  files:
    - "data/combined_data_1.txt"
    - "data/combined_data_2.txt"
    - "data/combined_data_3.txt"
    - "data/combined_data_4.txt"
  chunk_size: 100_000


model_save_path: "checkpoints/model.pkl"