data:
  rating_files:
    - "data/combined_data_1.txt"
    - "data/combined_data_2.txt"
    - "data/combined_data_3.txt"
    - "data/combined_data_4.txt"
  probe_file: "data/probe.txt"
  movie_titles_file: "data/movie_titles.csv"
  chunk_size: 100_000

output_dir: "checkpoints/"
